FROM openjdk:17-jdk-slim-buster
# 빌드목적
ARG JAR_FILENAME='inqueue-service'
ARG PACKAGE_JAR_LOCATION=/build/libs/*.jar
ARG VERSION

# 실행목적
# docker run --e 로 오버라이딩
ENV COMMAND_LINE_ARGS_BEFORE=${COMMAND_LINE_ARGS_BEFORE}
ENV COMMAND_LINE_ARGS_AFTER=${COMMAND_LINE_ARGS_AFTER}
ENV SERVER_PORT=8888
ENV VERSION=$VERSION

ADD ${PACKAGE_JAR_LOCATION} /app.jar

RUN echo ${VERSION}

EXPOSE ${SERVER_PORT}:8080
ENTRYPOINT java ${COMMAND_LINE_ARGS_BEFRE} ${VERSION} -jar ./app.jar ${COMMAND_LINE_ARGS_AFTER}