spring:
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      auto-commit: false
  h2:
     console:
       enabled: true
       path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: ture
    open-in-view: false

customer:
  account:
    client-id-length: 32
    client-secret-length: 64
